---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "20.04"


inputs:
  - name: domtest-pipeline

run:
  path: domtest-pipeline/tasks/scripts/hello-world.sh
