name: Close Done Issues on Friday Evening

on:
  schedule:
    - cron: '0 17 * * 5' # Runs at 5 PM UTC every Friday
  workflow_dispatch: # Allows for manual triggering

jobs:
  close_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Authenticate with GitHub CLI
        run: echo "$GH_TOKEN" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Close Done Issues
        run: |
          # List all open issues with the 'done' label
          issues=$(gh issue list --label "done" --state closed --json number --jq '.[].number')
          printenv issues

          # Close each issue with the 'done' label
          for issue in $issues; do
            gh issue close $issue -c "Closed automatically by GitHub Action because it was marked as done."
          done
